Repository pixano/pixano, pull requests merged in 2024-01, with the labels that each got.

#20 allow smooth drag of input point
  ui/components/canvas2d/src/Canvas2D.svelte
Labels: enhancement, scope: front

#21 feat(api): Add support for S3 datasets
  CHANGELOG.md
  docs/user/launch.md
  pixano/apps/main.py
  pixano/core/image.py
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_info.py
  pixano/data/dataset/dataset_stat.py
  pixano/data/item/item_view.py
  pixano/data/settings.py
  pyproject.toml
Labels: enhancement, scope: api

#26 feat(ci): Add backend linting
  .github/workflows/.pylintrc
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CHANGELOG.md
  notebooks/datasets/template_importer.py
  notebooks/models/interactive_annotation.ipynb
  notebooks/models/pre_annotation.ipynb
  notebooks/types/create_custom_type.ipynb
  pixano/analytics/feature_statistics.py
  pixano/apps/annotator/serve.py
  pixano/apps/api/datasets.py
  pixano/apps/api/items.py
  pixano/apps/api/models.py
  pixano/apps/display.py
  pixano/apps/explorer/serve.py
  pixano/apps/serve.py
  pixano/core/bbox.py
  pixano/core/camera.py
  pixano/core/depth_image.py
  pixano/core/image.py
  pixano/core/pixano_type.py
  pixano/core/pose.py
  pixano/core/utils.py
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_info.py
  pixano/data/dataset/dataset_item.py
  pixano/data/dataset/dataset_stat.py
  pixano/data/exporters/coco_exporter.py
  pixano/data/exporters/exporter.py
  pixano/data/fields.py
  pixano/data/importers/coco_importer.py
  pixano/data/importers/dota_importer.py
  pixano/data/importers/image_importer.py
  pixano/data/importers/importer.py
  pixano/data/item/item_object.py
  pixano/data/item/item_view.py
  pixano/data/settings.py
  pixano/models/inference_model.py
  pixano/utils/image.py
  pixano/utils/python.py
  pyproject.toml
  tests/apps/test_main.py
  tests/core/test_bbox.py
  tests/core/test_compressed_rle.py
  tests/core/test_depth_image.py
  tests/core/test_image.py
  tests/core/test_pose.py
  tests/core/test_utils.py
  tests/data/dataset/test_dataset.py
  tests/data/dataset/test_dataset_info.py
  tests/data/dataset/test_dataset_stats.py
  tests/data/exporters/test_coco_exporter.py
  tests/data/importers/test_coco_importer.py
  tests/data/importers/test_dota_importer.py
  tests/data/importers/test_image_importer.py
  tests/data/test_fields.py
  tests/data/test_settings.py
Labels: enhancement, scope: back

#27 feat(back): Merge Pixano apps in backend and docs
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/assets/user/app_annotation.png
  docs/assets/user/app_elementview.png
  docs/assets/user/app_home.png
  docs/assets/user/explorer_elementview.png
  docs/assets/user/explorer_exploration.png
  docs/assets/user/explorer_home.png
  docs/code/index.md
  docs/user/app.md
  docs/user/explorer.md
  docs/user/index.md
  docs/user/launch.md
  mkdocs.yml
  notebooks/datasets/import_dataset.ipynb
  notebooks/models/interactive_annotation.ipynb
  notebooks/models/pre_annotation.ipynb
  notebooks/models/semantic_search.ipynb
  pixano/app/README.md
  pixano/app/__init__.py
  pixano/app/api/__init__.py
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/app/api/models.py
  pixano/app/display.py
  pixano/app/main.py
  pixano/app/serve.py
  pixano/apps/__init__.py
  pixano/apps/annotator/README.md
  pixano/apps/annotator/__init__.py
  pixano/apps/annotator/serve.py
  pixano/apps/explorer/serve.py
  pixano/core/image.py
  pixano/data/dataset/dataset.py
  pixano/data/exporters/coco_exporter.py
  pixano/data/item/item_view.py
  pyproject.toml
  tests/app/__init__.py
  tests/app/test_main.py
  tests/core/test_image.py
Labels: scope: docs, enhancement, scope: back

#31 fix(back): missing test case for first dataset object
  pixano/data/dataset/dataset.py
Labels: bug, scope: back

#30 feat(front): Select models if more than one and display errors
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/components/modals/SelectModal.svelte
  ui/components/core/src/components/modals/WarningModal.svelte
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/LoadModelModal.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/imageWorkspace/src/lib/api/modelsApi.ts
  ui/components/imageWorkspace/src/lib/stores/imageWorkspaceStores.ts
  ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
Labels: enhancement, scope: front

#32 feat(front): Add back semantic search in dataset page
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/lib/types/pixanoTypes.ts
  ui/apps/pixano/src/routes/+layout.svelte
Labels: enhancement, scope: front

#29 chore: Fix Pixano deployed app
  .github/workflows/publish.yml
  CHANGELOG.md
  CONTRIBUTING.md
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/app/api/models.py
  pixano/app/main.py
  pixano/app/serve.py
  pixano/data/__init__.py
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_info.py
  pixano/data/dataset/dataset_stat.py
  pixano/data/importers/importer.py
  pixano/data/settings.py
  pyproject.toml
  tests/app/test_main.py
  tests/data/dataset/test_dataset.py
  tests/data/test_settings.py
  ui/apps/pixano/src/routes/+page.ts
  ui/apps/pixano/svelte.config.js
Labels: enhancement, scope: back

#33 feat: Load dynamic image parameters
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_item.py
  pixano/data/item/item_feature.py
  pixano/data/item/item_object.py
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte
  ui/components/imageWorkspace/src/components/Features/FeatureInputs.svelte
  ui/components/imageWorkspace/src/components/Features/ListInputFeature.svelte
  ui/components/imageWorkspace/src/components/Features/TextInputFeature.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/lib/api/featuresApi.ts
  ui/components/imageWorkspace/src/lib/settings/defaultFeatures.ts
  ui/components/imageWorkspace/src/lib/settings/objectValidationSchemas.ts
  ui/components/imageWorkspace/src/lib/stores/imageWorkspaceStores.ts
  ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
Labels: enhancement, scope: front

#36 feat: Add loading indicator on homepage
  ui/apps/pixano/src/components/layout/MainHeader.svelte
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/+page.svelte
Labels: enhancement, scope: front

#34 feat: Edit masks
  ui/apps/pixano/src/routes/+layout.svelte
  ui/components/canvas2d/package.json
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/api/maskApi.ts
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/lib/types/canvas2dTypes.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/assets/MagicIcon.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
  ui/components/imageWorkspace/src/components/ImageCanvas.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/models/src/Sam.ts
  ui/components/models/src/mask_utils.ts
Labels: enhancement, scope: front

#35 feat(front): Add favicon.ico and remove favicon.png
  ui/apps/pixano/src/assets/favicon.ico
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/static/favicon.ico
  ui/apps/pixano/static/favicon.png
Labels: enhancement, scope: front

#38 feat(front): Improve save item changes
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ActionsTabs.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
  ui/components/imageWorkspace/src/components/ImageCanvas.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
Labels: enhancement, scope: front

#41 fix(front): Improve multi-view and tool selection
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/lib/types/canvas2dTypes.ts
  ui/components/core/src/components/modals/ConfirmModal.svelte
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/Features/TextInputFeature.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/imageWorkspace/src/lib/settings/defaultFeatures.ts
Labels: enhancement, scope: front

#40 feat: Merge dtype and field format to improve feature saving
  pixano/core/__init__.py
  pixano/core/pixano_type.py
  pixano/core/utils.py
  pixano/data/__init__.py
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_item.py
  pixano/data/fields.py
  pixano/data/item/item_feature.py
  pixano/data/item/item_object.py
  pixano/data/item/item_view.py
  tests/core/test_utils.py
  ui/components/core/src/cell_types.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/components/Features/FeatureInputs.svelte
  ui/components/imageWorkspace/src/components/Features/TextInputFeature.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/lib/api/featuresApi.ts
  ui/components/imageWorkspace/src/lib/settings/defaultFeatures.ts
  ui/components/imageWorkspace/src/lib/settings/objectValidationSchemas.ts
  ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
  ui/components/table/src/Table.svelte
  ui/components/table/src/TableCell.svelte
  ui/components/table/src/TableCells/BooleanCell.svelte
  ui/tools/storybook/stories/components/imageWorkspace/imagerWorkspaceMock.ts
  ui/tools/storybook/stories/components/table/TableCell.stories.ts
Labels: enhancement, scope: front, scope: back

#42 chore(front): Various visual fixes
  ui/apps/pixano/src/components/dashboard/Dashboard.svelte
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/layout/MainHeader.svelte
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dashboard/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/components/modals/ConfirmModal.svelte
  ui/components/core/src/components/modals/PromptModal.svelte
  ui/components/core/src/components/modals/SelectModal.svelte
  ui/components/core/src/components/modals/WarningModal.svelte
  ui/components/core/src/components/ui/molecules/PrimaryButton.svelte
  ui/components/core/src/components/ui/tabs/tabs-trigger.svelte
  ui/components/core/src/components/ui/tooltip/tooltip-content.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ActionsTabs.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte
  ui/components/imageWorkspace/src/components/Features/FeatureInputs.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/table/src/Table.svelte
Labels: enhancement, scope: front

#43 chore(front): Fix navigation issues
  pixano/data/item/item_view.py
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/routes/+layout.svelte
Labels: enhancement, scope: front

#45 fix: Add default scene feature when loading for the first time
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte
Labels: bug, scope: front

#44 fix: Update object visibility in ObjectTabModelContent component
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabContent.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
Labels: bug, scope: front

#46 feat(back): allow dataset stats loading
  pixano/analytics/__init__.py
  pixano/analytics/image_statistics.py
  pixano/app/api/datasets.py
  pixano/data/dataset/dataset_stat.py
  ui/apps/pixano/src/routes/[dataset]/dashboard/+page.svelte
Labels: enhancement, scope: back

#52 fix: Fixed scaling issue in addBBox function
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
Labels: bug, scope: front

#54 feat(front): Improve visibility of first point of a polygon
  ui/components/canvas2d/src/components/PolygonGroup.svelte
Labels: enhancement

#53 fix(front): Load embeddings only once a model is selected
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/imageWorkspace/src/components/LoadModelModal.svelte
Labels: bug, scope: front

#51 feat: Update InferenceModel and pixano-inference
  .github/workflows/test.yml
  notebooks/models/pre_annotation.ipynb
  pixano/models/inference_model.py
Labels: enhancement, scope: back

#57 fix(front): Generate unique IDs when saving new object
  ui/components/imageWorkspace/package.json
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
Labels: bug

#63 fix(front): Keep modified points when creating a polygon
  ui/components/canvas2d/src/components/PolygonGroup.svelte
Labels: bug, scope: front

#61 fix(front): Remove shapes when canceling the annotation, #60
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
Labels: bug, scope: front

#64 fix(back): Fix formatting for new stable version of black
  .github/workflows/format.yml
  pixano/data/dataset/dataset.py
  pixano/data/exporters/coco_exporter.py
  pixano/data/importers/coco_importer.py
  pixano/data/item/item_object.py
  pixano/models/inference_model.py
Labels: enhancement, scope: back

#58 feat(front): Create pre-annotation
  pixano/data/dataset/dataset.py
  pixano/data/item/item_feature.py
  pixano/data/item/item_object.py
  ui/apps/pixano/src/components/dashboard/Dashboard.svelte
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/apps/pixano/src/components/layout/MainHeader.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/lib/types/canvas2dTypes.ts
  ui/components/core/src/components/ui/molecules/PrimaryButton.svelte
  ui/components/core/src/components/ui/molecules/TooltipIconButton.svelte
  ui/components/core/src/components/ui/slider/SliderRoot.svelte
  ui/components/core/src/components/ui/slider/index.ts
  ui/components/core/src/components/ui/switch/SwitchRoot.svelte
  ui/components/core/src/components/ui/switch/index.ts
  ui/components/core/src/components/ui/tabs/tabs-list.svelte
  ui/components/core/src/components/ui/tabs/tabs-trigger.svelte
  ui/components/core/src/index.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ActionsTabs.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabContent.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabLabelsItem.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte
  ui/components/imageWorkspace/src/components/Features/FeatureFormInputs.svelte
  ui/components/imageWorkspace/src/components/Features/FeatureInputs.svelte
  ui/components/imageWorkspace/src/components/Features/ListInputFeature.svelte
  ui/components/imageWorkspace/src/components/Features/TextInputFeature.svelte
  ui/components/imageWorkspace/src/components/ImageCanvas.svelte
  ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/imageWorkspace/src/lib/constants.ts
  ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
Labels: enhancement, scope: front

#65 feat(front): Create concave polygons
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/components/CreatePolygon.svelte
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/PolygonPoints.svelte
  ui/components/core/src/lib/types/objectTypes.ts
Labels: bug, enhancement

#68 feat(front): Allow dragging rectangle when edit mode is on
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
Labels: enhancement, scope: front
