Repository pixano/pixano, pull requests merged in 2024-07, with the labels that each got.

#291 Refactor dataset builders, tracklets and add creation of features
  pixano/datasets/__init__.py
  pixano/datasets/builders/__init__.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folder_based_builder.py
  pixano/datasets/builders/folders/__init__.py
  pixano/datasets/builders/folders/base.py
  pixano/datasets/builders/folders/image.py
  pixano/datasets/builders/folders/video.py
  pixano/datasets/dataset.py
  pixano/datasets/dataset_library.py
  pixano/datasets/dataset_schema.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/__init__.py
  pixano/datasets/features/schemas/image.py
  pixano/datasets/features/schemas/image_object.py
  pixano/datasets/features/schemas/item.py
  pixano/datasets/features/schemas/object.py
  pixano/datasets/features/schemas/point_cloud.py
  pixano/datasets/features/schemas/sequence_frame.py
  pixano/datasets/features/schemas/track_object.py
  pixano/datasets/features/schemas/tracklet.py
  pixano/datasets/features/schemas/video.py
  pixano/datasets/features/schemas/view.py
  pixano/datasets/features/types/__init__.py
  pixano/datasets/features/types/bbox.py
  pixano/datasets/features/types/bbox3d.py
  pixano/datasets/features/types/camcalibration.py
  pixano/datasets/features/types/compressed_rle.py
  pixano/datasets/features/types/keypoints.py
  pixano/datasets/features/types/keypoints3d.py
  pixano/datasets/features/types/nd_array_float.py
  pixano/datasets/features/types/registry.py
  pixano/datasets/features/utils/__init__.py
  pixano/datasets/features/utils/creators.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/python.py
  pixano/datasets/utils/video.py
  tests/assets/sample_data/image_jpg.jpg
  tests/assets/sample_data/image_png.png
  tests/assets/sample_data/video_mp4.mp4
  tests/check_license_header.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/builders/test_folders.py
Labels: scope: api, priority: high

#292 Fix/track object
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/track_object.py
  pixano/datasets/features/types/keypoints.py
Labels: scope: back, bug: major

#297 Test types schemas
  pixano/datasets/builders/folders/base.py
  pixano/datasets/features/schemas/base_schema.py
  pixano/datasets/features/schemas/embedding.py
  pixano/datasets/features/schemas/image.py
  pixano/datasets/features/schemas/image_object.py
  pixano/datasets/features/schemas/item.py
  pixano/datasets/features/schemas/object.py
  pixano/datasets/features/schemas/point_cloud.py
  pixano/datasets/features/schemas/sequence_frame.py
  pixano/datasets/features/schemas/track_object.py
  pixano/datasets/features/schemas/tracklet.py
  pixano/datasets/features/schemas/video.py
  pixano/datasets/features/schemas/view.py
  pixano/datasets/features/types/__init__.py
  pixano/datasets/features/types/base_type.py
  pixano/datasets/features/types/bbox.py
  pixano/datasets/features/types/bbox3d.py
  pixano/datasets/features/types/camcalibration.py
  pixano/datasets/features/types/compressed_rle.py
  pixano/datasets/features/types/keypoints.py
  pixano/datasets/features/types/keypoints3d.py
  pixano/datasets/features/types/nd_array_float.py
  pixano/datasets/features/types/registry.py
  pixano/datasets/features/utils/creators.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/image.py
  pixano/datasets/utils/python.py
  tests/datasets/builders/test_folders.py
  tests/datasets/features/__init__.py
  tests/datasets/features/schemas/__init__.py
  tests/datasets/features/schemas/test_base_schema.py
  tests/datasets/features/schemas/test_embedding.py
  tests/datasets/features/schemas/test_image.py
  tests/datasets/features/schemas/test_image_object.py
  tests/datasets/features/schemas/test_item.py
  tests/datasets/features/schemas/test_object.py
  tests/datasets/features/schemas/test_point_cloud.py
  tests/datasets/features/schemas/test_registry.py
  tests/datasets/features/schemas/test_sequence_frame.py
  tests/datasets/features/schemas/test_track_object.py
  tests/datasets/features/schemas/test_tracklet.py
  tests/datasets/features/schemas/test_video.py
  tests/datasets/features/schemas/test_view.py
  tests/datasets/features/test_image.py
  tests/datasets/features/test_pose.py
  tests/datasets/features/types/__init__.py
  tests/datasets/features/types/test_bbox.py
  tests/datasets/features/types/test_bbox3d.py
  tests/datasets/features/types/test_camcalibration.py
  tests/datasets/features/types/test_compressed_rle.py
  tests/datasets/features/types/test_keypoints.py
  tests/datasets/features/types/test_keypoints3d.py
  tests/datasets/features/types/test_nd_array_float.py
  tests/datasets/features/types/test_registry.py
  tests/datasets/features/utils.py
Labels: scope: tests

#296 Fix/multiview issues
  pixano/app/api/items.py
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/components/CreateKeypoints.svelte
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/canvas2d/src/components/ShowKeypoint.svelte
  ui/components/canvas2d/src/components/keypoints/Keypoint.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/tools/storybook/postcss.config.cjs
  ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts
Labels: scope: front, scope: back, bug: major

#299 Refactor datasets tests
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/annotations/camcalibration.py
  pixano/datasets/features/types/__init__.py
  pixano/datasets/features/types/schema_reference.py
  pixano/datasets/utils/creators.py
  pixano/datasets/utils/image.py
  tests/datasets/exporters/__init__.py
  tests/datasets/exporters/test_coco_exporter.py
  tests/datasets/features/test_image.py
  tests/datasets/features/test_pose.py
  tests/datasets/importers/__init__.py
  tests/datasets/importers/test_coco_importer.py
  tests/datasets/importers/test_dota_importer.py
  tests/datasets/importers/test_image_importer.py
  tests/datasets/test_dataset.py
  tests/datasets/test_dataset_info.py
  tests/datasets/test_dataset_stats.py
  tests/datasets/test_fields.py
  tests/datasets/test_settings.py
  tests/datasets/utils/__init__.py
  tests/datasets/utils/test_boxes.py
  tests/datasets/utils/test_creators.py
  tests/datasets/utils/test_image.py
  tests/datasets/utils/test_labels.py
  tests/datasets/utils/test_python.py
  tests/datasets/utils/test_video.py
  tests/features/test_bbox.py
  tests/features/test_camera.py
  tests/features/test_compressed_rle.py
  tests/features/test_depth_image.py
  tests/features/test_gt_info.py
  tests/features/test_image.py
  tests/features/test_pose.py
  tests/features/test_utils.py
  tests/utils/__init__.py
  tests/utils/test_boxes.py
  tests/utils/test_image.py
  tests/utils/test_labels.py
Labels: scope: tests

#300 Feat/back refactor datasets
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/datasets/__init__.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folders/base.py
  pixano/datasets/dataset.py
  pixano/datasets/dataset_explorer.py
  pixano/datasets/dataset_features_values.py
  pixano/datasets/dataset_info.py
  pixano/datasets/dataset_schema.py
  pixano/datasets/dataset_stat.py
  pixano/datasets/dataset_table.py
  pixano/datasets/features/schemas/base_schema.py
  pixano/datasets/features/schemas/registry.py
  pixano/datasets/features/types/registry.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/python.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/builders/test_folders.py
  tests/datasets/features/schemas/test_base_schema.py
  tests/datasets/features/schemas/test_registry.py
  tests/datasets/features/types/test_registry.py
  tests/datasets/test_dataset.py
  tests/datasets/test_dataset_explorer.py
  tests/datasets/test_dataset_features_values.py
  tests/datasets/test_dataset_info.py
  tests/datasets/test_dataset_schema.py
  tests/datasets/test_dataset_stat.py
  tests/datasets/utils/test_python.py
Labels: scope: back, scope: tests

#303 Refactor tracklet
  pixano/datasets/dataset_schema.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/__init__.py
  pixano/datasets/features/schemas/annotations/__init__.py
  pixano/datasets/features/schemas/annotations/tracklet.py
  pixano/datasets/features/schemas/entities/__init__.py
  pixano/datasets/features/schemas/entities/track.py
  pixano/datasets/features/types/__init__.py
  pixano/datasets/features/types/schema_reference.py
  pixano/datasets/utils/creators.py
  tests/datasets/features/schemas/annotations/test_tracklet.py
  tests/datasets/features/schemas/entities/test_track.py
  tests/datasets/utils/test_creators.py
Labels: scope: back

#301 Refactor/adapt rest api
  pixano/app/api/items.py
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
Labels: scope: front, scope: back

#305 performance upgrades
  pixano/app/api/items.py
  pixano/app/settings.py
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
Labels: scope: front

#307 Remove/Deprecated stuff in repository
  .github/workflows/lint_and_format_back.yml
  .github/workflows/test_back.yml
  CHANGELOG.md
  docs/getting_started/exporting_datasets.md
  docs/getting_started/importing_datasets.md
  mkdocs.yml
  notebooks/datasets/export_dataset.ipynb
  notebooks/datasets/import_dataset.ipynb
  notebooks/models/interactive_annotation.ipynb
  notebooks/models/pre_annotation.ipynb
  notebooks/models/semantic_search.ipynb
  notebooks/types/create_custom_type.ipynb
  pyproject.toml
Labels: scope: docs, scope: back, scope: tests

#308 tracklets per view
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
Labels: enhancement, scope: front

#311 limit objects features to top level entity
  pixano/app/api/items.py
Labels: scope: back

#315 Add ViewEmbedding
  pixano/datasets/dataset.py
  pixano/datasets/dataset_schema.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/pyarrow_utils.py
  pixano/datasets/features/schemas/__init__.py
  pixano/datasets/features/schemas/base_schema.py
  pixano/datasets/features/schemas/embeddings/__init__.py
  pixano/datasets/features/schemas/embeddings/embedding.py
  pixano/datasets/features/schemas/views/image.py
  pixano/datasets/features/types/schema_reference_typed.py
  pyproject.toml
  tests/datasets/conftest.py
  tests/datasets/features/schemas/embeddings/test_embedding.py
  tests/datasets/features/schemas/test_base_schema.py
  tests/datasets/test_dataset.py
  tests/datasets/test_dataset_schema.py
  tests/fixtures/datasets/features/embedding.py
Labels: scope: back, priority: high

#318 Docs/simplify_docstrings
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/app/api/models.py
  pixano/app/display.py
  pixano/app/main.py
  pixano/app/serve.py
  pixano/app/settings.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folders/base.py
  pixano/datasets/dataset.py
  pixano/datasets/dataset_explorer.py
  pixano/datasets/dataset_features_values.py
  pixano/datasets/dataset_info.py
  pixano/datasets/dataset_schema.py
  pixano/datasets/dataset_stat.py
  pixano/datasets/features/schemas/annotations/annotation.py
  pixano/datasets/features/schemas/annotations/bbox.py
  pixano/datasets/features/schemas/annotations/camcalibration.py
  pixano/datasets/features/schemas/annotations/compressed_rle.py
  pixano/datasets/features/schemas/annotations/keypoints.py
  pixano/datasets/features/schemas/annotations/tracklet.py
  pixano/datasets/features/schemas/base_schema.py
  pixano/datasets/features/schemas/embeddings/embedding.py
  pixano/datasets/features/schemas/entities/track.py
  pixano/datasets/features/schemas/items/item.py
  pixano/datasets/features/schemas/registry.py
  pixano/datasets/features/schemas/views/image.py
  pixano/datasets/features/schemas/views/point_cloud.py
  pixano/datasets/features/schemas/views/sequence_frame.py
  pixano/datasets/features/schemas/views/video.py
  pixano/datasets/features/types/nd_array_float.py
  pixano/datasets/utils/boxes.py
  pixano/datasets/utils/image.py
  pixano/datasets/utils/labels.py
  pixano/datasets/utils/python.py
  pixano/datasets/utils/video.py
Labels: scope: docs, priority: medium

#321 tests/first api tests
  pixano/app/api/datasets.py
  pixano/app/settings.py
  tests/app/__init__.py
  tests/app/api/__init__.py
  tests/app/api/test_datasets.py
  tests/app/test_settings.py
Labels: scope: api, scope: tests
