Repository pixano/pixano, pull requests merged in 2024-12, with the labels that each got.

#377 bugfix unknown image type
  pixano/features/utils/image.py
  tests/features/utils/test_image.py
Labels: bug: minor, scope: back

#376 fixed tracklet size
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
Labels: scope: front, bug: major

#391 fix colorScale with sub entities
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: bug: minor, scope: front

#388 Fix/sam tutorial
  docs/tutorials/segmentation_powered_by_sam.md
  pixano/app/models/embeddings.py
  pixano/datasets/dataset.py
  pixano/datasets/queries/table.py
  pixano/features/schemas/embeddings/embedding.py
  pyproject.toml
  tests/datasets/test_dataset.py
  tests/features/schemas/embeddings/test_embedding.py
  tests/fixtures/features/embedding.py
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/lib/api/modelsApi.ts
Labels: scope: back
