Repository pixano/pixano, pull requests merged in 2024-11, with the labels that each got.

#347 correction for higlight & editing status
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/rectangleApi.ts
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
Labels: scope: front

#351 Grouped deletion
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/api.ts
Labels: enhancement, scope: front

#353 Refactor semantic search in Dataset
  pixano/app/routers/browser.py
  pixano/datasets/dataset.py
  tests/datasets/test_dataset.py
Labels: scope: back, scope: api

#356 display features extent
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts
Labels: scope: front

#355 Bring back SAM
  docs/tutorials/segmentation_powered_by_sam.md
  mkdocs.yml
  pixano/app/main.py
  pixano/app/routers/models.py
  pixano/datasets/dataset_info.py
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/apps/pixano/vite.config.ts
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
  ui/components/datasetItemWorkspace/src/lib/api/modelsApi.ts
  ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
Labels: scope: front, scope: api, priority: high

#358 add a frame buffer for faster play
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
Labels: enhancement, scope: front

#360 manage sources
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Features/AutoCompleteFeatureInput.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/constants.ts
  ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
Labels: enhancement, scope: front

#365 Separate bounding box xywh conversion from denormalization in frontend
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
Labels: bug: minor, scope: front

#370 fix(front): Fix getCurrentImageTime()
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
Labels: bug: minor, scope: front

#369 thumbnails in browser
  pixano/app/routers/browser.py
  pixano/datasets/dataset_info.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/image.py
  pixano/features/schemas/embeddings/embedding.py
  pixano/features/schemas/views/image.py
  pixano/features/utils/image.py
  pyproject.toml
  tests/datasets/test_dataset.py
  tests/datasets/utils/test_image.py
  tests/features/schemas/embeddings/test_embedding.py
  tests/features/schemas/views/test_image.py
  tests/features/utils/test_image.py
  tests/fixtures/features/embedding.py
Labels: enhancement, scope: back

#368 circular buffer
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
Labels: enhancement, scope: front, bug: major
