Repository pixano/pixano, pull requests merged in 2024-06, with the labels that each got.

#260 feat(back): save item + video: Tracklet table handle
  pixano/app/api/items.py
  pixano/datasets/dataset.py
  pixano/datasets/features/schemas/tracklet.py
Labels: enhancement, scope: back

#262 feat(back): track_objet native class
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/track_object.py
Labels: enhancement, scope: back

#264 None predefined types
  pixano/datasets/features/types/bbox.py
  pixano/datasets/features/types/bbox3d.py
  pixano/datasets/features/types/camcalibration.py
  pixano/datasets/features/types/compressed_rle.py
  pixano/datasets/features/types/keypoints.py
  pixano/datasets/features/types/nd_array_float.py
Labels: enhancement, scope: back

#266 fix(back): save and load for empty bbox and mask
  pixano/app/api/items.py
Labels: scope: back, bug: major

#273 feat(back): keypoints
  pixano/app/api/items.py
  pixano/datasets/builders/folder_based_builder.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/object.py
  pixano/datasets/features/types/keypoints.py
  pixano/datasets/features/types/keypoints3d.py
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/keyPointsApi.ts
  ui/components/canvas2d/src/components/CreateKeypoints.svelte
  ui/components/canvas2d/src/components/ShowKeypoint.svelte
  ui/components/canvas2d/src/components/keypoints/Keypoint.svelte
  ui/components/canvas2d/src/components/keypoints/KeypointsCircle.svelte
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar/KeyPointsSelectionTool.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/settings/keyPointsTemplates.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: enhancement, scope: back

#276 fix(back): better management of some data errors/specific cases
  pixano/app/api/items.py
  pixano/datasets/builders/dataset_builder.py
Labels: enhancement, scope: back

#275 fix: Adapt keypoints creation background size
  ui/components/canvas2d/src/api/keypointsApi.ts
  ui/components/canvas2d/src/components/CreateKeypoints.svelte
  ui/components/canvas2d/src/components/ShowKeypoint.svelte
  ui/components/datasetItemWorkspace/src/lib/settings/keyPointsTemplates.ts
Labels: enhancement, scope: front

#281 feat(front): fix keypoints background position
  ui/components/canvas2d/src/components/CreateKeypoints.svelte
Labels: bug: minor, scope: front, priority: medium

#250 feat(front): Add image adjustment tools
  ui/components/canvas2d/package.json
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/lib/types/canvas2dTypes.ts
  ui/components/core/src/components/ui/switch/SwitchRoot.svelte
  ui/components/datasetItemWorkspace/package.json
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
  ui/components/table/src/Table.svelte
  ui/pnpm-lock.yaml
  ui/tools/storybook/.storybook/main.ts
  ui/tools/storybook/assets/tiff.png
  ui/tools/storybook/package.json
  ui/tools/storybook/stories/components/table/TableCell.stories.ts
  ui/tools/storybook/stories/components/table/tableMocks.ts
  ui/tools/storybook/stories/components/workspaces/ImageWorkspace.stories.ts
  ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts
  ui/tools/storybook/stories/vite.env.d.ts
Labels: enhancement, scope: front, priority: low

#279 feat(front) : Add an image smoothing toggle in settings
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: enhancement, scope: front

#278 feat(front): Add keypoints on video
  docs/restAPI_reference/data_items.md
  pixano/app/api/items.py
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts
Labels: enhancement, scope: front

#282 change version to 0.5.4
  pixano/__version__.py
Labels: release

#284 fix(front): fix sliders linked together
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
Labels: bug: minor, scope: front, priority: medium
