Repository pixano/pixano, pull requests merged in 2024-10, with the labels that each got.

#333 Add integrity checks
  pixano/app/routers/items_info.py
  pixano/app/routers/utils.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/dataset.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/errors.py
  pixano/datasets/utils/integrity.py
  tests/app/routers/test_utils.py
  tests/conftest.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/test_dataset.py
  tests/datasets/utils/test_integrity.py
  tests/fixtures/app/routers/models/annotations.py
  tests/fixtures/datasets/builders/builder.py
  tests/fixtures/datasets/dataset.py
  tests/fixtures/features/entity.py
Labels: enhancement, scope: back, priority: medium

#334 Add source to builder
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folders/base.py
  pixano/features/schemas/annotations/bbox.py
  pixano/features/schemas/annotations/camcalibration.py
  pixano/features/schemas/annotations/compressed_rle.py
  pixano/features/schemas/annotations/keypoints.py
  pixano/features/schemas/annotations/tracklet.py
  pixano/features/schemas/source.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/builders/test_folders.py
  tests/features/schemas/test_source.py
  tests/fixtures/datasets/builders/builder.py
Labels: scope: back

#335 Feat/text features : first implems of text-annotation types to Pixano
  pixano/features/__init__.py
  pixano/features/schemas/__init__.py
  pixano/features/schemas/annotations/__init__.py
  pixano/features/schemas/annotations/bbox.py
  pixano/features/schemas/annotations/classification.py
  pixano/features/schemas/annotations/info_extraction.py
  pixano/features/schemas/views/__init__.py
  pixano/features/schemas/views/text.py
  pixano/utils/__init__.py
  pixano/utils/python.py
  tests/features/schemas/annotations/test_classification.py
  tests/features/schemas/annotations/test_information_extraction.py
  tests/features/schemas/views/test_text.py
  tests/utils/test_python.py
Labels: enhancement, scope: back, priority: high

#337 Ci/remove develop and add version
  .github/workflows/license_check.yml
  .github/workflows/lint_and_format_back.yml
  .github/workflows/lint_and_format_front.yml
  .github/workflows/publish.yml
  .github/workflows/test_back.yml
  .github/workflows/update_versions.yml
  VERSION
  pyproject.toml
  ui/apps/pixano/package.json
Labels: scope: ci

#339 Ci/improve serving
  .dockerignore
  .github/workflows/docker.yml
  .github/workflows/publish.yml
  Dockerfile
  pixano/app/main.py
  pixano/app/routers/browser.py
  pixano/app/routers/dataset_items.py
  pixano/app/routers/datasets.py
  pixano/app/routers/items_info.py
  pixano/app/routers/utils.py
  pixano/app/serve.py
  pixano/app/settings.py
  pixano/datasets/builders/folders/base.py
  pixano/features/schemas/views/image.py
  pixano/features/schemas/views/sequence_frame.py
  pixano/features/schemas/views/video.py
  tests/app/routers/test_browser.py
  tests/app/routers/test_dataset_items.py
  tests/app/routers/test_datasets.py
  tests/app/routers/test_items_info.py
  tests/app/routers/utils.py
  tests/app/test_settings.py
  tests/datasets/builders/test_folders.py
  tests/features/schemas/views/test_image.py
  tests/features/schemas/views/test_sequence_frame.py
  tests/features/schemas/views/test_video.py
  tests/fixtures/app/app.py
Labels: enhancement, scope: api, scope: ci, priority: high

#330 WIP - Apply new back DataModel to front
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/layout/MainHeader.svelte
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/apps/pixano/vite.config.ts
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/api/maskApi.ts
  ui/components/canvas2d/src/api/rectangleApi.ts
  ui/components/canvas2d/src/components/CreateKeypoints.svelte
  ui/components/canvas2d/src/components/CreatePolygon.svelte
  ui/components/canvas2d/src/components/CreateRectangle.svelte
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/PolygonPoints.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/canvas2d/src/components/ShowKeypoint.svelte
  ui/components/canvas2d/src/components/keypoints/Keypoint.svelte
  ui/components/canvas2d/src/components/keypoints/KeypointsCircle.svelte
  ui/components/core/package.json
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/modelsTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
  ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar/KeyPointsSelectionTool.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/modelsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/settings/keyPointsTemplates.ts
  ui/components/datasetItemWorkspace/src/lib/settings/objectValidationSchemas.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/components/datasetItemWorkspace/src/lib/stores/videoViewerStores.ts
  ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
  ui/components/models/src/interfaces.ts
  ui/components/models/src/mask_utils.ts
  ui/components/table/src/Table.svelte
  ui/components/table/src/cells.ts
  ui/pnpm-lock.yaml
Labels: enhancement, scope: front, priority: high

#341 Add possibility to use where statement for getting data
  pixano/app/routers/annotations.py
  pixano/app/routers/browser.py
  pixano/app/routers/embeddings.py
  pixano/app/routers/entities.py
  pixano/app/routers/items.py
  pixano/app/routers/items_info.py
  pixano/app/routers/sources.py
  pixano/app/routers/utils.py
  pixano/app/routers/views.py
  pixano/datasets/dataset.py
  tests/app/routers/test_annotations.py
  tests/app/routers/test_embeddings.py
  tests/app/routers/test_entities.py
  tests/app/routers/test_items.py
  tests/app/routers/test_items_info.py
  tests/app/routers/test_source.py
  tests/app/routers/test_utils.py
  tests/app/routers/test_views.py
  tests/app/routers/utils.py
  tests/datasets/test_dataset.py
Labels: scope: back, scope: api

#343 Add constraint to prevent id with whitespaces
  pixano/app/models/base_schema.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/dataset_info.py
  pixano/features/schemas/base_schema.py
  tests/app/models/test_base_schema.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/test_dataset_info.py
  tests/features/schemas/test_base_schema.py
Labels: scope: back

#345 Prevent docker workflow to launch every time, fix update_version for PR only
  .github/workflows/docker.yml
  .github/workflows/update_versions.yml
Labels: scope: ci
