Repository pixano/pixano, pull requests merged in 2024-05, with the labels that each got.

#245 fix(back): allow add/update/delete of several item in one pass
  pixano/data/dataset/dataset.py
  pixano/models/inference_model.py
Labels: bug: minor, scope: back

#249 feat(back): change to version 0.5.2
  pixano/__version__.py
Labels: release

#247 Merge last front/back changes in new API main branch
  docs/restAPI_reference/data_items.md
  pixano/app/api/datasets.py
  pixano/app/api/items.py
  pixano/datasets/__init__.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folder_based_builder.py
  pixano/datasets/dataset.py
  pixano/datasets/dataset_explorer.py
  pixano/datasets/dataset_library.py
  pixano/datasets/dataset_table.py
  pixano/datasets/features/__init__.py
  pixano/datasets/features/schemas/image.py
  pixano/datasets/features/schemas/point_cloud.py
  pixano/datasets/features/types/bbox3d.py
  pixano/datasets/features/types/camcalibration.py
  pixano/datasets/features/types/keypoints.py
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/library/DatasetsLibrary.svelte
  ui/apps/pixano/src/lib/api/navigationApi.ts
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyBox.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoPlayer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoPlayerRow.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/components/datasetItemWorkspace/src/lib/stores/videoViewerStores.ts
  ui/components/table/src/Table.svelte
  ui/components/table/src/TableCell.svelte
  ui/components/table/src/TableCell.ts
  ui/components/table/src/index.ts
  ui/tools/storybook/stories/components/workspaces/videoDatasetPayload.ts
Labels: scope: front, scope: back, scope: api

#252 fix(front): navigation fix
  pixano/app/README.md
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/table/src/Table.svelte
  ui/components/table/src/cells.ts
Labels: scope: front, bug: major

#254 feat(back) change to version 0.5.3
  pixano/__version__.py
Labels: release

#257 fix(back): add is_key & rename keyBoxes to boxes
  pixano/app/api/items.py
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyBox.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts
  ui/tools/storybook/stories/components/workspaces/videoDatasetPayload.ts
Labels: scope: front, scope: back, scope: api

#256 Fix (front) : Tab title disappearing after refresh
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/+page.svelte
Labels: bug: minor, scope: front, priority: low
