Repository pixano/pixano, pull requests merged in 2024-02, with the labels that each got.

#67 feat(tests): Improve pixano.core unit tests
  pixano/core/__init__.py
  pixano/core/depth_image.py
  pixano/core/utils.py
  tests/core/test_bbox.py
  tests/core/test_camera.py
  tests/core/test_depth_image.py
  tests/core/test_gt_info.py
  tests/core/test_image.py
  tests/core/test_utils.py
Labels: enhancement, scope: tests

#78 feat(front): Destroy rectangle smart rectangle once smart mask is created
  ui/components/canvas2d/src/Canvas2D.svelte
Labels: enhancement, scope: front

#86 chore: Update version to 0.5.0b3
  pixano/__version__.py
Labels: release

#84 fix(front): Reset search when changing dataset
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/lib/types/pixanoTypes.ts
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dashboard/+page.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/components/CreatePolygon.svelte
  ui/components/core/src/api.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/table/src/Table.svelte
Labels: bug, enhancement, scope: front

#91 feat(back): Choose Pre-annotation or Model run in InferenceModel
  notebooks/models/pre_annotation.ipynb
  pixano/models/inference_model.py
  ui/.prettierrc.cjs
  ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
Labels: enhancement, scope: back

#92 fix(api): Create bounding box from mask automatically
  pixano/data/item/item_object.py
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
Labels: bug, scope: api

#87 feat(front): Create fixed size sections for Ground truth and Model run
  ui/components/core/src/components/ui/combobox/combobox.svelte
  ui/components/core/src/components/ui/tabs/tabs-trigger.svelte
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabContent.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabLabelsItem.svelte
  ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabLabelsSubItem.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ArrowSvg.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ImageInspector.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsInspector.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsModelSection.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/SceneInspector.svelte
  ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
Labels: enhancement, scope: front

#104 fix(back): Don't save review_state if None
  pixano/data/item/item_object.py
Labels: enhancement, scope: back

#105 feat(front): Select object by clicking them
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/api/boundingBoxesApi.ts
  ui/components/canvas2d/src/api/rectangleApi.ts
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/canvas2d/src/lib/types/canvas2dTypes.ts
  ui/components/core/src/components/ui/slider/SliderRoot.svelte
  ui/components/core/src/components/ui/switch/SwitchRoot.svelte
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/imageWorkspace/src/components/ImageCanvas.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ImageInspector.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsInspector.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsModelSection.svelte
  ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
  ui/components/imageWorkspace/src/lib/constants.ts
Labels: enhancement, scope: front

#109 fix(front): Allow zero to be shown in model run number of object
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsInspector.svelte
Labels: bug, scope: front

#107 feat(front): Switch tabs order in image inspector
  ui/components/imageWorkspace/src/components/ImageInspector/ImageInspector.svelte
Labels: enhancement, scope: front

#108 feat(front): Sort preannoted objects by axis
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
Labels: enhancement, scope: front

#111 feat(front): Delete lock feature
  ui/components/core/src/assets/icons/lockIcon.svg
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
Labels: enhancement, scope: front

#115 fix(front): Fix buttons in Toolbar
  ui/components/imageWorkspace/src/components/Toolbar.svelte
  ui/components/imageWorkspace/src/lib/settings/selectionTools.ts
Labels: enhancement, scope: front

#117 fix(front): Fix buttons in ImageInspector
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectsModelSection.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/SceneInspector.svelte
Labels: enhancement, scope: front

#120 fix(front): Fix buttons in DatasetHeader
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
Labels: enhancement, scope: front

#124 fix(front): Fix issues with loading segmentation models
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/imageWorkspace/src/components/LoadModelModal.svelte
  ui/components/imageWorkspace/src/lib/api/modelsApi.ts
Labels: enhancement, scope: front

#121 fix(front): Only allow object selection when PAN tool is activated
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/PolygonPoints.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
Labels: bug, scope: front

#122 fix(front): Autofocus only the first input in Feature Form
  ui/components/imageWorkspace/src/components/Features/FeatureFormInputs.svelte
Labels: bug, scope: front

#129 fix(front): Do not mutate object if id does not match
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
Labels: bug, scope: front

#102 feat(back): Add new MobileSAM model
  notebooks/models/interactive_annotation.ipynb
Labels: enhancement, scope: back

#130 feat(ci): Add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/feat_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/fix_pull_request.md
Labels: enhancement, scope: ci

#131 fix(front): Refetch saved item
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/lib/api/objectsApi.ts
Labels: bug, scope: front

#136 fix(front): Allow saving when deleting a selected object
  ui/components/imageWorkspace/src/components/ImageCanvas.svelte
Labels: bug, scope: front

#139 fix(front): reshape bbox with positive height/width
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
Labels: bug, scope: front

#140 fix(front): add cancel option to no embeddings modal
  ui/components/imageWorkspace/src/components/LoadModelModal.svelte
Labels: bug, scope: front

#138 fix(back): correct AWS env var name
  pixano/app/serve.py
Labels: bug, scope: back

#146 fix(ci): Merge pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/feat_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/fix_pull_request.md
Labels: bug: minor, scope: ci

#127 feat: Add features auto-completion
  pixano/app/api/datasets.py
  pixano/data/dataset/dataset.py
  pixano/data/dataset/dataset_info.py
  pixano/data/item/item_feature.py
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/components/ui/command/command-input.svelte
  ui/components/core/src/components/ui/command/command.svelte
  ui/components/core/src/components/ui/input/input.svelte
  ui/components/core/src/index.ts
  ui/components/core/src/lib/types/datasetTypes.ts
  ui/components/imageWorkspace/src/ImageWorkspace.svelte
  ui/components/imageWorkspace/src/components/Features/AutoCompleteFeatureInput.svelte
  ui/components/imageWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/imageWorkspace/src/components/Features/SelectFeatureInput.svelte
  ui/components/imageWorkspace/src/components/Features/TextFeatureInput.svelte
  ui/components/imageWorkspace/src/components/Features/UpdateFeatureInputs.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
  ui/components/imageWorkspace/src/components/ImageInspector/SceneInspector.svelte
  ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/imageWorkspace/src/lib/api/featuresApi.ts
  ui/components/imageWorkspace/src/lib/stores/imageWorkspaceStores.ts
Labels: enhancement, scope: front, scope: back, priority: high

#151 fix(front): Reset saveCurrentItemStore to false after navigating
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
Labels: bug: minor, scope: front, priority: medium

#135 chore: Freaze lockfile in CI
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .gitignore
  ui/pnpm-lock.yaml
Labels: enhancement, scope: ci, priority: medium

#150 fix(front): Do not add random transform shape after deleting an object
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/api/rectangleApi.ts
  ui/components/canvas2d/src/components/Rectangle.svelte
Labels: bug: minor, scope: front, priority: medium

#144 feat(docs): Update documentation for 0.5.0 release
  docs/assets/user/annotation_bounding_box.png
  docs/assets/user/annotation_polygon.png
  docs/assets/user/annotation_sam_points.png
  docs/assets/user/annotation_sam_rectangle.png
  docs/assets/user/app_annotation.png
  docs/assets/user/app_dashboard.png
  docs/assets/user/app_dataset_1.png
  docs/assets/user/app_dataset_2.png
  docs/assets/user/app_elementview.png
  docs/assets/user/app_home.png
  docs/assets/user/exploration_object_edition.png
  docs/assets/user/exploration_objects.png
  docs/assets/user/exploration_scene.png
  docs/code/index.md
  docs/gen_ref_pages.py
  docs/user/app.md
  docs/user/launch.md
  pixano/app/README.md
  pixano/core/pose.py
Labels: scope: docs, enhancement, priority: high

#164 fix(front): Recommandations for pre annotation are updated for each item
  ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
Labels: scope: front

#172 fix(front): Improve how stats are displayed in the app
  ui/apps/pixano/package.json
  ui/apps/pixano/src/components/dashboard/Dashboard.svelte
  ui/components/canvas2d/package.json
  ui/components/canvas3d/package.json
  ui/components/core/package.json
  ui/components/core/src/components/Histogram.svelte
  ui/components/core/src/components/colors.ts
  ui/components/datasetItemWorkspace/package.json
  ui/components/models/package.json
  ui/components/table/package.json
  ui/package.json
  ui/pnpm-lock.yaml
  ui/tools/storybook/package.json
  ui/tools/storybook/stories/components/Histogram.stories.ts
Labels: enhancement, scope: front, priority: medium

#169 fix(back): inference_model: don't rely on db/media table order
  pixano/models/inference_model.py
Labels: bug: minor, scope: back

#180 fix(front): Fix Objects disappear on click in pre-annotation mode
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: bug: minor, scope: front
