Repository pixano/pixano, pull requests merged in 2025-02, with the labels that each got.

#429 Refresh thumbnails whenever needed
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedEntity.ts
Labels: bug: minor, scope: front

#430 track fusion: add shortcuts for validate and abort
  ui/components/datasetItemWorkspace/src/components/Toolbar/FusionTool.svelte
Labels: enhancement, scope: front

#441 Add python3.13 support
  .github/workflows/lint_and_format_back.yml
  .github/workflows/test_back.yml
  pyproject.toml
Labels: scope: ci

#446 add loading icon when loading embeddings
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
Labels: enhancement, scope: front, priority: low

#448 fix highlighted selected entity when sub entities
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
Labels: bug: minor, scope: front

#452 feat(front): Small dataset page enhancements
  ui/components/table/src/Table.svelte
  ui/components/table/src/TableCell.ts
  ui/components/table/src/TableCells/DateTimeCell.svelte
Labels: enhancement, scope: front

#451 feat(front): Small homepage enhancements
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/apps/pixano/src/components/layout/MainHeader.svelte
Labels: enhancement, scope: front

#450 feat(front): Keep fusion tool selected
  ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
Labels: enhancement, scope: front

#457 feat(front): Disable focus and scrolling on spacebar shortcut
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
Labels: enhancement, scope: front

#456 SaveItem update: check with id and ALSO table_info
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/addOrUpdateSaveItem.ts
Labels: scope: front, bug: major

#463 Feat/update app header
  ui/apps/pixano/src/components/dataset/DatasetBrowserForm.svelte
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/dataset/DatasetPagination.svelte
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/assets/MagicIcon.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar/FusionTool.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar/KeyPointsSelectionTool.svelte
  ui/components/datasetItemWorkspace/src/lib/settings/keyPointsTemplates.ts
  ui/components/datasetItemWorkspace/src/lib/settings/selectionTools.ts
  ui/components/table/src/Table.svelte
Labels: scope: front

#444 folder builders rework
  pixano/app/routers/views.py
  pixano/datasets/builders/folders/base.py
  pixano/datasets/builders/folders/image.py
  pixano/datasets/builders/folders/vqa.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/mosaic.py
  pixano/datasets/workspaces/dataset_items.py
  pixano/features/schemas/annotations/text_generation.py
  pixano/features/schemas/entities/conversation.py
  tests/conftest.py
  tests/datasets/builders/test_dataset_builder.py
  tests/datasets/builders/test_folders.py
  tests/features/schemas/annotations/test_information_extraction.py
  tests/features/schemas/annotations/test_text_generation.py
  tests/features/schemas/entities/test_conversation.py
  tests/fixtures/datasets/builders/builder.py
  tests/fixtures/datasets/builders/folder.py
  tests/fixtures/datasets/dataset.py
  tests/fixtures/datasets/dataset_info.py
  tests/fixtures/datasets/dataset_item.py
  ui/components/core/src/lib/types/dataset/annotations/Message.ts
  ui/components/core/src/lib/types/dataset/entities/Conversation.ts
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedEntity.ts
  ui/components/datasetItemWorkspace/src/lib/stores/mutations/addAnswer.ts
  ui/components/datasetItemWorkspace/src/lib/stores/mutations/updateMessageContent.ts
  ui/components/datasetItemWorkspace/src/lib/utils/createNewAnswer.ts
  ui/components/datasetItemWorkspace/src/lib/utils/createUpdatedAnswer.ts
  ui/components/vqaCanvas/src/components/FormattedAnswer.svelte
  ui/components/vqaCanvas/src/components/MultipleChoiceAnswer.svelte
  ui/components/vqaCanvas/src/components/OpenAnswer.svelte
  ui/components/vqaCanvas/src/components/QuestionForm.svelte
  ui/components/vqaCanvas/src/components/SingleChoiceAnswer.svelte
  ui/components/vqaCanvas/src/lib/types/ContentChangeEvent.ts
  ui/components/vqaCanvas/src/lib/utils/answerChoicesToCheckboxsState.ts
  ui/components/vqaCanvas/src/lib/utils/checkboxsStateToAnswerChoices.ts
  ui/components/vqaCanvas/src/lib/utils/deserializeMessageContent.ts
  ui/components/vqaCanvas/src/lib/utils/index.ts
  ui/components/vqaCanvas/src/lib/utils/isQuestionCompleted.ts
  ui/components/vqaCanvas/src/lib/utils/serializeMessageContent.ts
  ui/tools/storybook/stories/testing/datasetSchema.ts
  ui/tools/storybook/stories/testing/datasets/mockEntityLinkingDatasetItem.ts
  ui/tools/storybook/stories/testing/datasets/mockVqaDatasetItem.ts
Labels: enhancement, scope: back

#466 Fix docker build
  .github/workflows/docker.yml
  Dockerfile
Labels: scope: ci, bug: major, priority: high

#462 feat: Add COCO exporter
  pixano/app/serve.py
  pixano/datasets/exporters/__init__.py
  pixano/datasets/exporters/coco_dataset_exporter.py
  pixano/datasets/exporters/dataset_exporter.py
  pixano/datasets/exporters/default.py
  pixano/datasets/exporters/default_json_dataset_exporter.py
  pixano/datasets/exporters/default_jsonl_dataset_exporter.py
  pixano/datasets/utils/__init__.py
  pixano/datasets/utils/labels.py
  pixano/features/schemas/annotations/compressed_rle.py
  pixano/features/types/registry.py
  pixano/features/utils/__init__.py
  pixano/features/utils/image.py
  tests/app/routers/test_dataset_items.py
  tests/datasets/exporters/test_coco_dataset_exporter.py
  tests/datasets/exporters/test_dataset_exporter.py
  tests/datasets/exporters/test_default_json_exporter.py
  tests/datasets/exporters/test_default_jsonl_exporter.py
  tests/datasets/utils/test_labels.py
  tests/features/schemas/annotations/test_compressed_rle.py
  tests/fixtures/datasets/builders/builder.py
Labels: enhancement, scope: back

#468 Feat/add vqa and image mask generation
  pixano/app/models/annotations.py
  pixano/app/models/sources.py
  pixano/datasets/dataset.py
  pixano/features/schemas/annotations/annotation.py
  pixano/features/types/nd_array_float.py
  pixano/features/types/registry.py
  pixano/inference/__init__.py
  pixano/inference/client.py
  pixano/inference/image_text_conditional_generation.py
  pixano/inference/mask_generation.py
  pyproject.toml
  tests/app/models/test_annotations.py
  tests/app/models/test_source.py
  tests/datasets/test_dataset.py
  tests/features/types/test_nd_array_float.py
  tests/fixtures/app/routers/models/annotations.py
  tests/fixtures/datasets/dataset_schema.py
  tests/fixtures/inference/client.py
  tests/inference/test_client.py
  tests/inference/test_image_text_conditional_generation.py
  tests/inference/test_mask_generation.py
  ui/components/core/src/lib/types/dataset/annotations/Annotation.ts
  ui/components/core/src/lib/types/dataset/sources/Source.ts
Labels: scope: back

#469 fix fake source metadata type
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
Labels: bug: minor, scope: front

#470 inference_metadata field front fixes + object total count fix
  ui/components/core/src/lib/types/dataset/annotations/Annotation.ts
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedObject.ts
Labels: bug: minor, scope: front

#471 Feat/rest inference
  pixano/app/main.py
  pixano/app/routers/inference/__init__.py
  pixano/app/routers/inference/conditional_generation.py
  pixano/app/routers/inference/models.py
  pixano/app/routers/inference/utils.py
  pixano/app/serve.py
  pixano/app/settings.py
  pixano/inference/__init__.py
  pixano/inference/text_image_conditional_generation.py
  tests/app/routers/test_datasets.py
  tests/app/routers/test_inference/__init__.py
  tests/app/routers/test_inference/test_conditional_generation.py
  tests/app/routers/test_inference/test_init.py
  tests/app/routers/test_inference/test_models.py
  tests/app/routers/test_inference/test_utils.py
  tests/conftest.py
  tests/datasets/test_dataset.py
  tests/fixtures/app/app.py
  tests/fixtures/app/models/dataset_info.py
  tests/fixtures/datasets/dataset.py
  tests/fixtures/inference/client.py
  tests/inference/test_text_image_conditional_generation.py
Labels: scope: api

#472 ops: upgrade node and pnpm
  .github/workflows/docker.yml
  .github/workflows/lint_and_format_front.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  Dockerfile
  ui/.eslintrc.cjs
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/canvas2d/src/components/PolygonPoints.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/core/src/components/ui/.eslintrc.cjs
  ui/components/core/src/components/ui/combobox/combobox.svelte
  ui/components/core/src/components/ui/command/command-input.svelte
  ui/components/core/src/components/ui/command/command-item.svelte
  ui/components/core/src/components/ui/command/command-list.svelte
  ui/components/core/src/components/ui/context-menu/context-menu-checkbox-item.svelte
  ui/components/core/src/components/ui/context-menu/context-menu-item.svelte
  ui/components/core/src/components/ui/context-menu/context-menu-radio-item.svelte
  ui/components/core/src/components/ui/context-menu/context-menu-sub-trigger.svelte
  ui/components/core/src/components/ui/dialog/dialog-portal.svelte
  ui/components/core/src/components/ui/histogram/Histogram.svelte
  ui/components/core/src/components/ui/input/input.svelte
  ui/components/core/src/lib/types/dataset/annotations/Annotation.ts
  ui/components/core/src/lib/types/dataset/annotations/Bbox.ts
  ui/components/core/src/lib/types/dataset/annotations/Classification.ts
  ui/components/core/src/lib/types/dataset/annotations/Keypoint.ts
  ui/components/core/src/lib/types/dataset/annotations/Mask.ts
  ui/components/core/src/lib/types/dataset/annotations/TextSpan.ts
  ui/components/core/src/lib/types/dataset/annotations/Tracklet.ts
  ui/components/core/src/lib/utils/annotations/createTypedAnnotation.ts
  ui/components/core/src/utils.ts
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectWithNewStatus.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/models/src/npy.ts
  ui/components/textCanvas/src/lib/utils/textSpansToHtml.ts
  ui/components/vqaCanvas/src/components/SingleChoiceAnswer.svelte
  ui/eslint.config.mjs
  ui/package.json
  ui/pnpm-lock.yaml
Labels: scope: ci

#474 Replace prints by logger.info
  pixano/__init__.py
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/exporters/dataset_exporter.py
Labels: scope: back

#480 Update to Pixano-Inference 0.5.0
  pixano/app/routers/inference/conditional_generation.py
  pixano/app/routers/inference/models.py
  pixano/inference/mask_generation.py
  pixano/inference/text_image_conditional_generation.py
  pyproject.toml
  tests/inference/test_mask_generation.py
  tests/inference/test_text_image_conditional_generation.py
Labels: scope: back, scope: ci

#477 Fix/dataset explorer
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
  ui/components/table/src/Table.svelte
Labels: bug: minor, scope: front

#479 Feat/text view class
  ui/components/core/src/lib/types/dataset/BaseSchema.ts
  ui/components/core/src/lib/types/dataset/views/SequenceFrame.ts
  ui/components/core/src/lib/types/dataset/views/TextView.ts
  ui/components/core/src/lib/types/dataset/views/index.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/index.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectToBBox.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectToKeypoints.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: enhancement, scope: front

#481 add a "cancel" button to SelectModal
  ui/components/core/src/components/modals/SelectModal.svelte
  ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
Labels: bug: minor, enhancement, scope: front

#483 Add image zero shot detection
  pixano/app/models/annotations.py
  pixano/app/models/base_schema.py
  pixano/app/models/dataset_items.py
  pixano/app/models/embeddings.py
  pixano/app/models/entities.py
  pixano/app/models/items.py
  pixano/app/models/sources.py
  pixano/app/models/views.py
  pixano/app/routers/dataset_items.py
  pixano/app/routers/inference/__init__.py
  pixano/app/routers/inference/conditional_generation.py
  pixano/app/routers/inference/utils.py
  pixano/app/routers/inference/zero_shot_detection.py
  pixano/app/routers/utils.py
  pixano/inference/__init__.py
  pixano/inference/mask_generation.py
  pixano/inference/text_image_conditional_generation.py
  pixano/inference/zero_shot_detection.py
  pyproject.toml
  tests/app/models/test_annotations.py
  tests/app/models/test_base_schema.py
  tests/app/models/test_dataset_items.py
  tests/app/models/test_embeddings.py
  tests/app/models/test_entities.py
  tests/app/models/test_items.py
  tests/app/models/test_source.py
  tests/app/models/test_views.py
  tests/app/routers/test_inference/test_conditional_generation.py
  tests/app/routers/test_inference/test_zero_shot_detection.py
  tests/fixtures/datasets/dataset_schema.py
  tests/inference/test_zero_shot_detection.py
Labels: scope: back

#484 Add arm platform
  .github/workflows/docker.yml
  .github/workflows/publish.yml
Labels: scope: ci

#487 v0.6.5
  VERSION
  pixano/__version__.py
  pyproject.toml
  ui/apps/pixano/package.json
Labels: scope: ci
