Repository pixano/pixano, pull requests merged in 2025-03, with the labels that each got.

#489 dataset thumbnail: get absolute path
  pixano/datasets/dataset_info.py
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
Labels: bug: minor, scope: front, scope: back

#447 FeaturesValues front replug
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/lib/types/dataset/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineTooltip.ts
  ui/components/datasetItemWorkspace/src/lib/settings/defaultFeatures.ts
Labels: scope: front

#490 fix regex vite.config
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/apps/pixano/vite.config.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: scope: front, bug: major

#492 generate thumbnail from text
  pixano/app/routers/browser.py
  pixano/features/utils/__init__.py
  pixano/features/utils/image.py
  tests/features/utils/test_image.py
Labels: enhancement, scope: back

#494 fix: autoresize-textarea component by forwarding the blur event
  ui/components/core/src/components/ui/autoresize-textarea/autoresize-textarea.svelte
Labels: bug: minor, scope: front

#495 add entity, bbox, ... tables to default vqa schema
  pixano/datasets/workspaces/dataset_items.py
  tests/datasets/builders/test_folders.py
Labels: bug: minor, scope: back

#493 remove types Track and Conversation
  ui/components/core/src/lib/types/dataset/entities/Conversation.ts
  ui/components/core/src/lib/types/dataset/entities/Entity.ts
  ui/components/core/src/lib/types/dataset/entities/Track.ts
  ui/components/core/src/lib/types/dataset/entities/index.ts
  ui/components/core/src/lib/types/inference/inference.ts
  ui/components/core/src/lib/utils/entities/createTypedEntity.ts
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedEntity.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/tools/storybook/stories/testing/datasets/mockEntityLinkingDatasetItem.ts
  ui/tools/storybook/stories/testing/datasets/mockVqaDatasetItem.ts
Labels: enhancement, scope: front

#497 show load icon while generating
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
  ui/components/vqaCanvas/src/VqaArea.svelte
  ui/components/vqaCanvas/src/features/addQuestion/components/AddQuestionModal.svelte
Labels: enhancement, scope: front

#496 merge VQAFolderBuilder in FolderBaseBuilder
  .github/workflows/test_back.yml
  pixano/datasets/builders/folders/base.py
  pixano/datasets/builders/folders/vqa.py
  pixano/features/utils/__init__.py
  tests/conftest.py
  tests/datasets/builders/test_folders.py
  tests/fixtures/datasets/builders/folder.py
Labels: enhancement, scope: back

#501 feat(front): Center tracklets in timeline
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
Labels: enhancement, scope: front

#502 feat(front): Disable changing frame index on right click
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
Labels: enhancement, scope: front

#503 feat(front): Highlighting and UI improvements
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/highlightObject.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/scrollIntoView.ts
Labels: enhancement, scope: front

#499 modal prompt & temperature
  pixano/app/routers/inference/conditional_generation.py
  pixano/inference/text_image_conditional_generation.py
  tests/inference/test_text_image_conditional_generation.py
  ui/components/core/src/index.ts
  ui/components/core/src/lib/types/inference/inference.ts
  ui/components/datasetItemWorkspace/src/lib/stores/mutations/generateAnswer.ts
  ui/components/datasetItemWorkspace/src/lib/stores/mutations/generateQuestion.ts
  ui/components/vqaCanvas/src/VqaArea.svelte
  ui/components/vqaCanvas/src/features/addQuestion/components/NewQuestionForm.svelte
  ui/components/vqaCanvas/src/features/annotateItem/components/OpenAnswer.svelte
  ui/components/vqaCanvas/src/features/manageModels/components/AddModelModal.svelte
  ui/components/vqaCanvas/src/features/manageModels/components/ConfigurePromptModal.svelte
  ui/components/vqaCanvas/src/features/manageModels/components/ConnectModal.svelte
  ui/components/vqaCanvas/src/features/manageModels/components/ModelManagerForm.svelte
  ui/components/vqaCanvas/src/features/manageModels/defaults.ts
  ui/components/vqaCanvas/src/stores/completionModels.ts
  ui/components/vqaCanvas/src/utils/mergeModelsList.ts
Labels: enhancement, scope: front, scope: back

#504 folder default item values & default conversation
  pixano/datasets/builders/folders/base.py
  tests/conftest.py
  tests/datasets/builders/test_folders.py
  tests/fixtures/datasets/builders/folder.py
Labels: bug: minor, enhancement, scope: back

#498 Feat/entity linking
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/lib/types/dataset/BaseSchema.ts
  ui/components/core/src/lib/types/dataset/DatasetItem.ts
  ui/components/core/src/lib/types/dataset/annotations/TextSpan.ts
  ui/components/core/src/lib/types/dataset/entities/Entity.ts
  ui/components/core/src/lib/types/dataset/views/Image.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/core/src/lib/utils/views/createTypedView.ts
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/textCanvas/src/TextSpanArea.svelte
  ui/components/textCanvas/src/components/SpannableTextView.svelte
  ui/components/textCanvas/src/components/index.ts
  ui/components/textCanvas/src/lib/utils/createHtmlTags.ts
  ui/components/textCanvas/src/lib/utils/editorSelectionToTextSpan.ts
  ui/components/textCanvas/src/lib/utils/groupTextSpansByViewId.ts
  ui/components/textCanvas/src/lib/utils/index.ts
  ui/components/vqaCanvas/src/features/manageModels/components/ModelManagerForm.svelte
  ui/tools/storybook/stories/testing/datasetSchema.ts
  ui/tools/storybook/stories/testing/datasets/mockEntityLinkingDatasetItem.ts
Labels: enhancement, scope: front

#505 allows segmentation for vqa and EL workspaces
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
Labels: bug: minor, scope: back

#510 feat(front): Change highlight frame only if outside of track bounds
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/highlightObject.ts
Labels: enhancement, scope: front

#511 textspan: compute background luminace to choose text color
  ui/components/textCanvas/src/lib/utils/createHtmlTags.ts
Labels: enhancement, scope: front

#515 fix(front): Minor UI fixes
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
Labels: enhancement, scope: front

#516 feat(ci): Update GitHub actions and templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/backend.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/frontend.yml
  .github/workflows/license_check.yml
  .github/workflows/publish.yml
  .github/workflows/test_back.yml
  .github/workflows/version.yml
Labels: enhancement, scope: ci

#517 feat: Update README badges
  README.md
Labels: enhancement

#506 folder builder change params
  docs/tutorials/create_your_first_library.md
  docs/tutorials/segmentation_powered_by_sam.md
  pixano/datasets/builders/dataset_builder.py
  pixano/datasets/builders/folders/base.py
  pixano/datasets/builders/folders/video.py
  tests/datasets/builders/test_folders.py
  tests/fixtures/datasets/builders/folder.py
Labels: scope: docs, enhancement, scope: back

#518 feat(docs): Update documentation and README
  README.md
  docs/getting_started/creating_a_dataset.md
  docs/getting_started/index.md
  docs/getting_started/key_concepts.md
  docs/tutorials/dataset.md
  docs/tutorials/index.md
  docs/tutorials/interactive_segmentation.md
  docs/tutorials/semantic_search.md
  mkdocs.yml
  pixano/datasets/dataset_schema.py
  pixano/features/schemas/annotations/info_extraction.py
  pixano/features/schemas/annotations/text_generation.py
  pixano/features/schemas/views/image.py
  pixano/inference/zero_shot_detection.py
Labels: scope: docs, enhancement, scope: back

#520 Set none limit to table size
  docs/tutorials/interactive_segmentation.md
  docs/tutorials/semantic_search.md
  pixano/datasets/dataset.py
  pixano/datasets/exporters/dataset_exporter.py
  tests/datasets/test_dataset.py
  ui/components/core/src/api/getSources.ts
Labels: enhancement, scope: back

#521 filter unique mentions
  ui/components/canvas2d/src/components/TextSpansContent.svelte
Labels: enhancement, scope: front
