Repository pixano/pixano, pull requests merged in 2025-07, with the labels that each got.

#568 add pre-annotation tutorial
  docs/tutorials/index.md
  docs/tutorials/pre_annotation.md
  mkdocs.yml
Labels: scope: docs, enhancement

#573 feat(front): Improve navigation keyboard shortcuts
  ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
Labels: enhancement, scope: front

#572 minor improvement/bugfixes on ObjectCard
  ui/components/canvas2d/src/components/TextSpansContent.svelte
  ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ChildCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/deleteObject.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/scrollIntoView.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: bug: minor, enhancement, scope: front

#574 add objects filters + some related adaptations
  ui/apps/pixano/src/components/dataset/DatasetBrowserForm.svelte
  ui/apps/pixano/src/components/dataset/FilterTable.svelte
  ui/components/core/src/components/ui/molecules/TooltipIconButton.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/FilterLine.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsSection.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/OptionsAndFilters.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/getTopEntity.ts
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
  ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
Labels: enhancement, scope: front

#575 allow features values (predefined) for Annotation
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
Labels: bug: minor, scope: front

#584 cosmetics changes
  ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
  ui/components/core/src/components/ui/molecules/TooltipIconButton.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/addOrUpdateSaveItem.ts
Labels: enhancement, scope: front

#587 add '/' to avoid redirect
  ui/components/core/src/api/getItemsInfo.ts
Labels: bug: minor, scope: back

#591 order by created_at
  pixano/datasets/queries/table.py
  ui/components/core/src/api/getBrowser.ts
Labels: enhancement, scope: back

#596 thumbnail back side dataset_preview
  pixano/datasets/dataset_info.py
Labels: enhancement, scope: back

#598 minor various fixes
  ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/OptionsAndFilters.svelte
Labels: bug: minor, scope: front

#599 fix ids order
  pixano/app/routers/browser.py
  pixano/datasets/queries/table.py
  ui/apps/pixano/src/lib/stores/datasetStores.ts
Labels: bug: minor, scope: front, scope: back
