Repository pixano/pixano, pull requests merged in 2025-04, with the labels that each got.

#512 fix(front): Fix issues with fusion tool
  ui/components/canvas2d/src/components/PolygonGroup.svelte
  ui/components/canvas2d/src/components/Rectangle.svelte
  ui/components/canvas2d/src/components/keypoints/Keypoint.svelte
  ui/components/core/src/lib/types/dataset/annotations/Annotation.ts
  ui/components/core/src/lib/types/dataset/annotations/Bbox.ts
  ui/components/core/src/lib/types/dataset/annotations/Classification.ts
  ui/components/core/src/lib/types/dataset/annotations/Keypoint.ts
  ui/components/core/src/lib/types/dataset/annotations/Mask.ts
  ui/components/core/src/lib/types/dataset/annotations/Message.ts
  ui/components/core/src/lib/types/dataset/annotations/TextSpan.ts
  ui/components/core/src/lib/types/dataset/annotations/Tracklet.ts
  ui/components/core/src/lib/types/dataset/datasetTypes.ts
  ui/components/core/src/lib/types/dataset/entities/Entity.ts
  ui/components/core/src/lib/types/objectTypes.ts
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
  ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar/FusionTool.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/highlightObject.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectToBBox.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectToMasks.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/mapObjectWithNewStatus.ts
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/updateExistingObject.ts
  ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
  ui/components/datasetItemWorkspace/src/lib/settings/selectionTools.ts
Labels: bug: minor, scope: front

#519 fix SAM loading model & emb table
  ui/apps/pixano/src/components/library/DatasetsLibrary.svelte
  ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
  ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
Labels: scope: front, bug: major, priority: high

#522 upgrade version 0.6.7
  VERSION
  pixano/__version__.py
  ui/apps/pixano/package.json
Labels: release

#523 fix(ci): Fix docs deployment conflicts
  .github/workflows/docs.yml
Labels: bug: minor, scope: docs, scope: ci

#526 update semantic search documentation
  docs/tutorials/semantic_search.md
Labels: scope: docs

#525 object inspector slider
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
Labels: enhancement, scope: front

#527 fix(front): Fix number of objects visible on frame
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
Labels: bug: minor, scope: front

#524 allow schema overwrite
  pixano/datasets/dataset.py
  pixano/datasets/dataset_schema.py
  tests/datasets/test_dataset_schema.py
Labels: enhancement, scope: back

#533 chore(front): Remove capitalization of names of object features
  ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
Labels: enhancement, scope: front

#537 TextSpan enhancements
  ui/components/textCanvas/src/TextSpanArea.svelte
  ui/components/textCanvas/src/components/SpannableTextView.svelte
  ui/components/textCanvas/src/lib/utils/createHtmlTags.ts
  ui/components/textCanvas/src/lib/utils/textSpansToHtml.ts
Labels: bug: minor, scope: front

#539 Allow filtering of datasetItems on browser page
  pixano/app/routers/browser.py
  ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/lib/stores/datasetStores.ts
  ui/apps/pixano/src/lib/types/pixanoTypes.ts
  ui/apps/pixano/src/routes/+layout.svelte
  ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
  ui/components/core/src/api/getBrowser.ts
  ui/components/core/src/api/getDatasetItemsIds.ts
  ui/components/table/package.json
  ui/components/table/src/Table.svelte
  ui/components/table/src/filterTable.svelte
  ui/pnpm-lock.yaml
Labels: enhancement, scope: front, scope: back

#541 add index of count in header
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
Labels: enhancement, scope: front
