Repository pixano/pixano, pull requests merged in 2025-01, with the labels that each got.

#399 feat: Add larger color palette
  ui/components/core/src/utils.ts
Labels: enhancement, scope: front

#404 show/hide track
  ui/components/core/src/lib/types/dataset/entities/Entity.ts
  ui/components/core/src/lib/types/dataset/entities/Track.ts
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
Labels: enhancement, scope: front

#403 Add shortcuts for play actions
  ui/components/canvas2d/src/Canvas2D.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
Labels: enhancement, scope: front

#401 gather save by method, group, table
  ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
  ui/components/core/src/api/addSchemas.ts
  ui/components/core/src/api/index.ts
  ui/components/core/src/api/updateSchemas.ts
  ui/components/core/src/lib/types/dataset/datasetTypes.ts
Labels: enhancement, scope: front

#405 feat(front): Better TimeTrack scaling
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
Labels: enhancement, scope: front

#409 feat(front): Estimate video speed
  ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
Labels: enhancement, scope: front

#414 shift for datasetItem change left&right arrow
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
Labels: bug: minor, scope: front

#417 fix(front): Add a minimum tracklet width
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
Labels: bug: minor, scope: front

#416 allow no jsonl
  pixano/datasets/builders/folders/base.py
Labels: enhancement, scope: back

#418 fix(front): Delete all empty tracks
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
Labels: bug: minor, scope: front

#419 feat(front): Add icons for timeline zoom slider
  ui/components/core/src/components/ui/slider/SliderRoot.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
Labels: enhancement, scope: front

#421 add key shortcut in tooltip
  ui/apps/pixano/src/components/layout/DatasetHeader.svelte
Labels: enhancement, scope: front

#423 feat(front): Update object thumbnails in side panel
  ui/components/canvas2d/src/components/Thumbnail.svelte
  ui/components/core/src/lib/types/dataset/datasetTypes.ts
  ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/DisplayCheckbox.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
  ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
  ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineObjectThumbnail.ts
Labels: enhancement, scope: front

#427 remove track from timeline if last tracklet
  ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
  ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
Labels: bug: minor, scope: front

#431 Add pixano-inference client
  mkdocs.yml
  pixano/inference/__init__.py
  pixano/inference/client.py
  pyproject.toml
  tests/conftest.py
  tests/fixtures/inference/__init__.py
  tests/fixtures/inference/client.py
  tests/inference/__init__.py
  tests/inference/test_client.py
Labels: scope: back, scope: ci
